jumphosts:
  hosts:
    Jumphost1:
      ansible_host: 192.168.0.108
      ansible_user: cloud_test
    Jumphost2:
      ansible_host: 192.168.0.242
      ansible_user: cloud_test
    Jumphost3:
      ansible_host: 192.168.0.129
      ansible_user: cloud_test
